project_id = "klxrjohcpaxviltzpxam"

[functions.add-admin-user]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.check-application-status]
verify_jwt = false

[functions.send-contact]
verify_jwt = false

[functions.notify-blog-submission]
verify_jwt = false

[functions.notify-author-approval]
verify_jwt = false
